title: 'PAIC | ITA'
baseurl: 'http://www.comp.ita.br/~verri/paic/'
copyright: '© {year} CAIC ITA'

defaultContentLanguage: pt
hasCJKLanguage: false
defaultContentLanguageInSubdir: false
removePathAccents: true

module:
  imports:
    - path: github.com/wowchemy/wowchemy-hugo-modules/wowchemy
  hugoVersion:
    min: '0.83.1'
    extended: true

enableGitInfo: true
summaryLength: 30
paginate: 10
enableEmoji: true
enableRobotsTXT: true
footnotereturnlinkcontents: <sup>^</sup>
ignoreFiles: [\.ipynb$, .ipynb_checkpoints$, \.Rmd$, \.Rmarkdown$, _cache$]
permalinks:
  authors: '/pessoa/:slug/'
  categories: '/categoria/:slug/'
  # tags: '/tag/:slug/'
  # publication_types: '/publication-type/:slug/'
disableAliases: true
outputs:
  home: [HTML, RSS, JSON, WebAppManifest, headers, redirects]
  section: [HTML, RSS]
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true
  highlight:
    codeFences: false
  tableOfContents:
    startLevel: 2
    endLevel: 3
imaging:
  resampleFilter: lanczos
  quality: 75
  anchor: smart
timeout: 600000
taxonomies:
  tag: tags
  category: categories
  publication_type: publication_types
  author: authors
related:
  threshold: 80
  includeNewer: true
  toLower: true
  indices:
    - name: tags
      weight: 100
    - name: categories
      weight: 70
