main:
  - name: Notícias
    url: post
    weight: 20
  - name: Modalidades
    url: modalidade
    weight: 25
  - name: Coordenação
    url: people
    weight: 30
  - name: ENCITA
    url: event
    weight: 40
  - name: Publicações
    url: publication
    weight: 50
