main:
  - name: Notícias
    url: noticia
    weight: 20
  - name: Modalidades
    url: modalidade
    weight: 25
  - name: Coordenação
    url: coordenacao
    weight: 30
  - name: Eventos
    url: evento
    weight: 40
#  - name: Publicações
#    url: publication
#    weight: 50
